二维数组案例

#include<iostream>
#include<string>
using namespace std;


int main()
{
	int arr[3][3] =
	{
		{100,100,100},
		{90,50,100},
		{60,70,80}
	};
	string names[3] = { "张三","李四","王五" };
	for (int i = 0; i < 3; i++)
	{
		int sum = 0;
		for (int j = 0; j < 3; j++)
		{
			sum += arr[i][j];
		}
		cout << names[i]<<"的总分为" << sum << endl;
	}

	system("pause");
	return 0;
}


函数调用


#include<iostream>
#include<string>
using namespace std;
//h函数类型
void  swap(int num1, int num2)
{
	cout << "交换前：" << endl;
	cout << "num1=" << num1 << endl;
	cout << "num2=" << num2<< endl;

	int temp = num1;
	num1 = num2;
	num2 = temp;

	cout << "交换后：" << endl;
	cout << "num1=" << num1 << endl;
	cout << "num2=" << num2 << endl;


}

int main()
{
	int a = 10;
	int b = 20;
	 
	swap(a, b);
	
	system("pause");
	return 0;
}
